

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MarshalUI(object):
    def setupUi(self, MarshalUI):
        MarshalUI.setObjectName("MarshalUI")
        MarshalUI.setMaximumSize(446, 804)
        MarshalUI.setWindowIcon(QtGui.QIcon("Body\\Logoicon.ico"))
        self.centralwidget = QtWidgets.QWidget(MarshalUI)
        self.centralwidget.setObjectName("centralwidget")
        self.centralwidget.setMinimumWidth(446)
        self.centralwidget.setMinimumHeight(804)
        self.centralwidget.setStyleSheet("background-color: black;")

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-26, -35, 471, 841))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Body\\Black_Template.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.Marshall = QtWidgets.QLabel(self.centralwidget)
        self.Marshall.setGeometry(QtCore.QRect(-45, -40, 530, 390))
        self.Marshall.setText("")
        self.Marshall.setPixmap(QtGui.QPixmap("Body\\siri_1.gif"))
        self.Marshall.setScaledContents(True)
        self.Marshall.setObjectName("Marshall")
        self.Mlogo = QtWidgets.QLabel(self.centralwidget)
        self.Mlogo.setGeometry(QtCore.QRect(289, 675, 221, 131))
        self.Mlogo.setText("")
        self.Mlogo.setPixmap(QtGui.QPixmap("Body\\M.gif"))
        self.Mlogo.setScaledContents(True)
        self.Mlogo.setObjectName("Mlogo")
        self.Mouth = QtWidgets.QLabel(self.centralwidget)
        self.Mouth.setGeometry(QtCore.QRect(-48, 230, 541, 220))
        self.Mouth.setText("")
        self.Mouth.setPixmap(QtGui.QPixmap("Body\\mouth.gif"))
        self.Mouth.setScaledContents(True)
        self.Mouth.setObjectName("Mouth")
        self.Face = QtWidgets.QLabel(self.centralwidget)
        self.Face.setGeometry(QtCore.QRect(100, 410, 241, 290))
        self.Face.setText("")
        self.Face.setPixmap(QtGui.QPixmap("Body\\AIface.gif"))
        self.Face.setScaledContents(True)
        self.Face.setObjectName("Face")

        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(-2, 400, 450, 291))
        self.frame.setAutoFillBackground(False)
        self.frame.setStyleSheet("font: 75 8pt \"8514oem\";\n"
"color : blue;\n"
"background-color: transparent;")
        self.frame.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setLineWidth(1)
        self.frame.setObjectName("frame")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.frame)
        self.plainTextEdit.setGeometry(QtCore.QRect(-1, 1, 451, 291))
        self.plainTextEdit.setAutoFillBackground(False)
        self.plainTextEdit.setStyleSheet("font: 75 8pt \"8514oem\";\n"
"color : skyblue;\n"
"background-color: transparent;")
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setMouseTracking(True)
        self.plainTextEdit.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.plainTextEdit.setFrameShadow(QtWidgets.QFrame.Plain)
        self.plainTextEdit.setBackgroundVisible(False)
        self.plainTextEdit.setObjectName("plainTextEdit")

        self.Mlogo2 = QtWidgets.QLabel(self.centralwidget)
        self.Mlogo2.setGeometry(QtCore.QRect(-65, 675, 221, 131))
        self.Mlogo2.setText("")
        self.Mlogo2.setPixmap(QtGui.QPixmap("Body\\M2.gif"))
        self.Mlogo2.setScaledContents(True)
        self.Mlogo2.setObjectName("Mlogo2")
        self.loading = QtWidgets.QLabel(self.centralwidget)
        self.loading.setGeometry(QtCore.QRect(140, 700, 161, 141))
        self.loading.setText("")
        self.loading.setPixmap(QtGui.QPixmap("Body\\loading.gif"))
        self.loading.setScaledContents(True)
        self.loading.setObjectName("loading")
        self.QUIT = QtWidgets.QPushButton(self.centralwidget)
        self.QUIT.setGeometry(QtCore.QRect(191, 710, 61, 20))
        self.QUIT.setStyleSheet("background-color : skyblue; border : 2px solid black; border-radius : 5px;")
        self.QUIT.setObjectName("QUIT")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(-46, -5, 2001, 1101))
        self.label_2.setText("Start")
        self.label_2.setPixmap(QtGui.QPixmap("Body\\Black_Template.jpg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")

        self.l = QtWidgets.QLabel(self.centralwidget)
        self.l.setGeometry(QtCore.QRect(-10, -20, 461, 101))
        self.l.setText("")
        self.l.setPixmap(QtGui.QPixmap("Body\\Desktop Assistant.png"))
        self.l.setScaledContents(True)
        self.l.setObjectName("l")
        
        self.label_2.raise_()
        self.label.raise_()
        self.Marshall.raise_()
        self.Mlogo.raise_()
        self.Mlogo2.raise_()
        self.Mouth.raise_()
        self.Face.raise_()
        self.plainTextEdit.raise_()
        self.frame.raise_()
        self.loading.raise_()
        self.QUIT.raise_()
        self.l.raise_()

        MarshalUI.setCentralWidget(self.centralwidget)
        self.retranslateUi(MarshalUI)
        QtCore.QMetaObject.connectSlotsByName(MarshalUI)

    def retranslateUi(self, MarshalUI):
        _translate = QtCore.QCoreApplication.translate
        MarshalUI.setWindowTitle(_translate("MarshalUI", "Desktop Assistant"))
        self.QUIT.setText(_translate("MarshalUI", "EXIT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MarshalUI = QtWidgets.QMainWindow()
    ui = Ui_MarshalUI()
    ui.setupUi(MarshalUI)
    MarshalUI.show()
    sys.exit(app.exec_())
